### ISSUE TITLE
Add XRD Plugin

### ISSUE THREAD

**Issue by hampusnasstrom** [FAIRmat-NFDI/nomad-measurements#1]

**Comment by budschi** [comment]
Hackathon day 2 tasks:

- [ ] sample id --> id, name , preparedBy --> @budschi 
- [ ] xy parser @hampusnasstrom 
- [ ] create a **basicELN_XRD** @hampusnasstrom 
- [ ] if time Bruker nad/or Rigaku files @budschi @hampusnasstrom 
- [ ] HTEM @hampusnasstrom
