### ISSUE TITLE
Conflict with Nomad plugin entry point  

### ISSUE THREAD

**Issue by RubelMozumder** [FAIRmat-NFDI/nomad-measurements#107]
I am having an issue installing the plugin using nomad entry point mechanism. After the inclusion of `XRD` plugin through the `nomad.yaml` config file, all installed plugin entry points are not available anymore. I added two figures here after and before installing `XRD`.

![After_including_XRD_with_nomad_yaml](https://github.com/user-attachments/assets/a911a757-1db0-4b41-aa38-c91f0e58cc3e)
![Before_including_XRD_plugin_via_nomad_yaml](https://github.com/user-attachments/assets/f9abb1d2-e692-4270-b079-52f788305f86)

Anyone of you have seen the issue before? How I can fix it, any idea?

**Comment by aalbino2** [comment]
You need to include explicitly all the entry points, once you introduce the use in "include" in nomad.yaml.

Fixed also with the discord discussion
