### ISSUE TITLE
Harmonize raw file class name

### ISSUE THREAD

**Issue by ka-sarthak** [FAIRmat-NFDI/nomad-measurements#71]
When generating an entry for the raw file, harmonize the name of the class with other schemas. For eg, class-name is standardized as `RawFile<tag-specific-to-the-technique>`

This is to standardize and improve the search-ability of various raw files.

**Comment by aalbino2** [comment]
@RoteKekse what do you think? We may harmonize all together this!

**Comment by RoteKekse** [comment]
Can you give some examples?

**Comment by RoteKekse** [comment]
But yeah good idea. It is for the metainfo class of the rawfile right. Which usually just contains a reference to the parsed data? It would be nice if there is a class to inherit from like RawFileELN and that the upload view is not showing them

**Comment by RoteKekse** [comment]
It is just that the upload page is so busy but maybe the new gui will address it anyhow

**Comment by aalbino2** [comment]
ok, then back to a common name for the class:

we have for example RawFileGrowthRun, RawFileDepositionControl, etc. depending on which class the raw file will populate.

As you mentioned, making a general RawFile class would allow us to search for all the rawfiles easier.
Then also using a convention for the subclasses names would be the best scenario, for example I'm now working in a [PLUGIN](https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/blob/main/LayTec_EpiTT/laytec_epitt_plugin/src/laytec_epitt/parser.py) and I found the name LayTecEpiTTFile.

Do you agree on using a same name format??

**Comment by RoteKekse** [comment]
i would say it makes sense that you recommend a notation. There is a good chance that i will forget next time i need to do it ^^

**Comment by aalbino2** [comment]
let's try to recall! I changed it in one use case of mine, I will check all of them and @ka-sarthak will do the same in XRD, @hampusnasstrom can you also harmonize yours?

We need the rawfile class, we need to decide where to place it. In basecetions.py?

**Comment by hampusnasstrom** [comment]
I would say that needs to go in the basesections.py yeah. There is still the question whether that is now being moved to a plugin or not but that's another discussion.

Just to be clear @aalbino2, it's the name of the class and not the name of the entry that you want to harmonize?

**Comment by aalbino2** [comment]
yes, correct!

**Comment by ka-sarthak** [comment]
I created a PR resolving this issue for XRD. @hampusnasstrom
