### ISSUE TITLE
Change of directory tree

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/nomad-measurements#72]
May i ask to delete the nomad_measurement folder inside the src? 

I think we may drop all the packages directly in src

@ka-sarthak will analyse this comment when he is back. @hampusnasstrom is it okay for you?

**Comment by hampusnasstrom** [comment]
What would be the reason for this? In `nomad-material-processing` we found quite a few general things that go in there and I could foresee the same here. But if you have a good reason I'm willing to reconsider ;)

**Comment by hampusnasstrom** [comment]
I would have to also have to redesign the PyPI pipeline and create new packages for each of the measurement methods.

**Comment by aalbino2** [comment]
isn't the path `nomad-measurements/src/nomad_measurements` redundant?

what would fall in `src` but not in the subfolder `nomad_measurements`?

**Comment by hampusnasstrom** [comment]
I think this is just standard python package practice but I'll have a look. Is it causing some issue for you?

**Comment by hampusnasstrom** [comment]
From some quick searching online:
[https://stackoverflow.com/questions/72712965/does-the-src-folder-in-pypi-packaging-have-a-special-meaning-or-is-it-only-a-co](https://stackoverflow.com/questions/72712965/does-the-src-folder-in-pypi-packaging-have-a-special-meaning-or-is-it-only-a-co)

**Comment by hampusnasstrom** [comment]
So I would keep it unless it's causing some issue for you?

**Comment by aalbino2** [comment]
`src` is okay! I mean the further `nomad_measurements` inside, one can have the `src` folder and, inside that, directly all the measuremnt packages (currently only xrd). Like this: 

```
IKZ_plugin/
├── nomad.yaml
├── src
│   ├── basesections_IKZ
│   ├── cz_IKZ
│   ├── ds_IKZ
│   ├── mbe_IKZ
│   └── movpe_IKZ
└── tests
    └── data
        ├── basesections_IKZ
        ├── cz_IKZ
        ├── ds_IKZ
        ├── mbe_IKZ
        └── movpe_IKZ
```

**Comment by hampusnasstrom** [comment]
Not if you want to package it as one python package. See the link I sent.

**Comment by hampusnasstrom** [comment]
I mean technically you could. But then you would install `nomad-measurements` and then get a bunch of access points like `cz_IKZ`, `ds_IKZ` and so on. Not sure if that is very nice.

**Comment by hampusnasstrom** [comment]
Is the issue just that you think it looks bad? Or that you don't want to type `from nomad-measurements.` every time? Or is something causing a technical issue?

**Comment by hampusnasstrom** [comment]
If we want to import them separately it might be better to create separate python packages for them. Which we will probably need to do in the end anyways to deal with the dependencies.

**Comment by aalbino2** [comment]
I'll keep this issue open so Sarthak will read as well. Then he can close it

**Comment by aalbino2** [comment]
> If we want to import them separately it might be better to create separate python packages for them. Which we will probably need to do in the end anyways to deal with the dependencies.

True. So we'll keep this in mind for this splitting of packages!
