### ISSUE TITLE
Improve XRD plots

### ISSUE THREAD

**Issue by hampusnasstrom** [FAIRmat-NFDI/nomad-measurements#86]
We should:

- [x] Put back the plotting for `intensity`, `two_theta`, and `q_norm` using **old annotations**
- [x] Make the labels prettier for the RSM plot (should be lower case q in italics with the parallel and perpendicular signs subscripted in my opinion)
- [x] Change the ticks of the log color bar to say 10 to the numbers (superscripted) and add a label to it
- [x] Add a name to the XRD result to make the workflow view look nicer

**Comment by Pepe-Marquez** [comment]
Is there a reason why the x-axis is locked and one cannot maximize?

**Comment by ka-sarthak** [comment]
@Pepe-Marquez I don't think there was any particular reason. I will add this to the upcoming improvements.

**Comment by ka-sarthak** [comment]
- [ ] Fix: when the ELNXRayDiffraction is started without a file, its plotting function already expects results and throws errors.
