### ISSUE TITLE
Add FileEditQuantity to Measurement ELN

### ISSUE THREAD

**Issue by A-D-Fuchs** [FAIRmat-NFDI/nomad-measurements#96]
It would be great to have an easy way to link measurement files (files created during a measurement, like: `.txt, .dat, .hdf5, .nxs, ...`) to the Base Sections "Measurement ELN". 
Or something like the "steps" where we can easy add a "Data" object where we then can drag and drop the data files.

**Comment by aalbino2** [comment]
@A-D-Fuchs the issue is moved here https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/2053, 
we will tackle it
