### ISSUE TITLE
Create a repo and a Pypi package for XRD reader

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/nomad-measurements#99]
Let'S clarify the best approach: 

One repo with multiple PyPi packages or small repos for each reader ? ?

Pros: better git workflow with one repo for each Pypi package
Cons: flooding the FAIRmat NFDI with a lot of repos for each reader

@hampusnasstrom @ka-sarthak I think we can discuss this in the next data modeling on wednesday

**Comment by aalbino2** [comment]
name for the repo: ` xrd_reader`

name for Pypi package: `fairmat_xrd_reader`

**Comment by ka-sarthak** [comment]
@aalbino2 Sounds great, so should I wait until our meeting before creating the new repo?

**Comment by aalbino2** [comment]
yes let's finalize on wednesday

**Comment by hampusnasstrom** [comment]
I would use hyphens instead of underscores but otherwise it sounds good. Yeah, let's do it on Wednesday.

**Comment by ka-sarthak** [comment]
Here's a PR to resolve this https://github.com/FAIRmat-NFDI/readers-xrd/pull/2
